package com.musab.dosyayoneticisi;

import android.app.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public abstract class BinaryEditorPlusActivity extends Activity {
 protected File file; protected LinearLayout root,list; protected TextView info; protected EditText search; protected byte[] pending; protected String selectedName="";
 protected abstract boolean isValid(byte[] data); protected abstract String formatInfo(byte[] data); protected abstract String getEditorName();
 @Override public void onCreate(Bundle b){super.onCreate(b);String p=getIntent().getStringExtra("path");if(p==null){finish();return;}file=new File(p);build();load();}
 protected void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(10,10,10,10);root.setBackgroundColor(Color.rgb(10,10,12));TextView title=t(getEditorName(),23,Color.WHITE);root.addView(title,new LinearLayout.LayoutParams(-1,64));info=t("Yükleniyor...",13,Color.LTGRAY);root.addView(info,new LinearLayout.LayoutParams(-1,66));LinearLayout bar=new LinearLayout(this);addBar(bar,"Yeni dosya",v->newVirtualFile());addBar(bar,"Yeni klasör",v->newVirtualFolder());addBar(bar,"Bul",v->findString());addBar(bar,"Hex",v->hexPatchDialog());addBar(bar,"Kaydet",v->saveData());addBar(bar,"Çık",v->finish());root.addView(bar,new LinearLayout.LayoutParams(-1,58));TextView path=t("İçerik",15,Color.WHITE);path.setPadding(8,10,8,6);root.addView(path,new LinearLayout.LayoutParams(-1,42));ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));search=new EditText(this);search.setHint("Kod/string ara");search.setTextColor(Color.WHITE);search.setHintTextColor(Color.GRAY);root.addView(search,new LinearLayout.LayoutParams(-1,54));setContentView(root);}
 private TextView t(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private void addBar(LinearLayout p,String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setAllCaps(false);b.setOnClickListener(l);p.addView(b,new LinearLayout.LayoutParams(0,58,1));}
 protected byte[] read()throws Exception{if(!file.isFile())throw new IOException("Dosya bulunamadı");if(file.length()>32L*1024*1024)throw new IOException("32 MB üzerindeki dosyalarda düzenleme kapalı");ByteArrayOutputStream o=new ByteArrayOutputStream();try(InputStream in=new FileInputStream(file)){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);}return o.toByteArray();}
 protected void load(){try{byte[] d=pending!=null?pending:read();info.setText(formatInfo(d)+"\nBoyut: "+d.length+" byte"+(isValid(d)?"":"\nUyarı: başlık beklenen formatta değil."));buildTree(d);}catch(Exception e){info.setText("Hata: "+e.getMessage());}}
 protected void buildTree(byte[] d){list.removeAllViews();addFolder("Header",()->showCode("Header",headerText(d)));addFolder("Kod / Stringler",()->showCode("Kod / Stringler",printable(d)));addFolder("Hex verisi",()->showCode("Hex verisi",hexDump(d)));addFolder("Yeni dosyalar",()->showWorkspace());}
 private void addFolder(String name,final Runnable r){LinearLayout row=new LinearLayout(this);row.setPadding(8,2,8,2);TextView icon=t("▸",24,Color.WHITE);TextView n=t(name,16,Color.WHITE);row.addView(icon,new LinearLayout.LayoutParams(45,58));row.addView(n,new LinearLayout.LayoutParams(0,58,1));row.setOnClickListener(v->{icon.setText("▾");r.run();});list.addView(row);}
 private void showCode(String name,String text){list.removeAllViews();TextView back=t("‹ İçeriğe dön",16,Color.WHITE);back.setPadding(8,8,8,8);back.setOnClickListener(v->load());list.addView(back);EditText ed=new EditText(this);ed.setText(text);ed.setTextColor(Color.WHITE);ed.setTextSize(13);ed.setTypeface(android.graphics.Typeface.MONOSPACE);ed.setGravity(Gravity.TOP);ed.setSingleLine(false);ed.setPadding(10,10,10,30);list.addView(ed,new LinearLayout.LayoutParams(-1,0,1));Button save=new Button(this);save.setText("Değiştir");save.setAllCaps(false);save.setOnClickListener(v->applyEditorText(name,ed.getText().toString()));list.addView(save,new LinearLayout.LayoutParams(-1,62));}
 private void applyEditorText(String name,String s){try{if("Kod / Stringler".equals(name)){byte[] d=pending!=null?pending:read();String old=selectedName;if(old.length()==0){info.setText("Önce Bul ile bir string seç.");return;}byte[] a=old.getBytes(StandardCharsets.UTF_8),b=s.getBytes(StandardCharsets.UTF_8);if(a.length!=b.length)throw new Exception("Yeni metnin byte uzunluğu aynı olmalı");int at=indexOf(d,a,0);if(at<0)throw new Exception("Seçilen metin bulunamadı");System.arraycopy(b,0,d,at,b.length);pending=d;info.setText("Değişiklik hazır. Kaydet'e bas.");}else info.setText("Bu görünüm bilgi amaçlıdır; yapısal başlık metnini geçersizleştirecek kayıt yapılmadı.");}catch(Exception e){info.setText("Düzenleme hatası: "+e.getMessage());}}
 private String headerText(byte[] d){StringBuilder s=new StringBuilder();s.append("Dosya: ").append(file.getName()).append('\n');s.append("İlk 16 byte: ");for(int i=0;i<Math.min(16,d.length);i++)s.append(String.format(Locale.US,"%02X ",d[i]&255));s.append('\n').append(formatInfo(d));return s.toString();}
 private String printable(byte[] d){StringBuilder s=new StringBuilder();int start=-1;for(int i=0;i<d.length;i++){int c=d[i]&255;boolean ok=c>=32&&c<127;if(ok&&start<0)start=i;if((!ok||i==d.length-1)&&start>=0){int end=ok&&i==d.length-1?i+1:i;if(end-start>=4){String x=new String(d,start,end-start,StandardCharsets.UTF_8);s.append(String.format(Locale.US,"%08X  ",start)).append(x).append('\n');}start=-1;}if(s.length()>80000)break;}if(s.length()==0)s.append("Yazdırılabilir metin yok.");return s.toString();}
 private String hexDump(byte[] d){StringBuilder s=new StringBuilder();int n=Math.min(4096,d.length);for(int i=0;i<n;i++){if(i%16==0)s.append(String.format(Locale.US,"%08X  ",i));s.append(String.format(Locale.US,"%02X ",d[i]&255));if(i%16==15)s.append('\n');}if(d.length>n)s.append("... ").append(d.length-n).append(" byte daha ...");return s.toString();}
 private void findString(){String q=search.getText().toString();if(q.isEmpty()){info.setText("Aranacak metni gir.");return;}try{byte[] d=pending!=null?pending:read(),n=q.getBytes(StandardCharsets.UTF_8);int at=indexOf(d,n,0);selectedName=q;info.setText(at>=0?"Bulundu: 0x"+Integer.toHexString(at)+" ("+at+")":"Bulunamadı: "+q);if(at>=0)showCode("Kod / Stringler",printable(d));}catch(Exception e){info.setText("Hata: "+e.getMessage());}}
 private void hexPatchDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText off=new EditText(this);off.setHint("Offset: 0x20 veya 32");EditText hx=new EditText(this);hx.setHint("Byte: 00 FF 41");box.addView(off);box.addView(hx);new AlertDialog.Builder(this).setTitle(getEditorName()+" — Hex düzenle").setView(box).setPositiveButton("Uygula",(d,w)->{try{byte[] data=pending!=null?pending:read();String os=off.getText().toString().trim().toLowerCase(Locale.ROOT);int o=os.startsWith("0x")?Integer.parseInt(os.substring(2),16):Integer.parseInt(os);String[] p=hx.getText().toString().trim().split("\\s+");if(o<0||o+p.length>data.length)throw new Exception("Offset aralık dışında");for(int i=0;i<p.length;i++)data[o+i]=(byte)Integer.parseInt(p[i],16);pending=data;load();info.setText("Hex yaması uygulandı. Kaydet'e bas.");}catch(Exception e){info.setText("Hex hatası: "+e.getMessage());}}).setNegativeButton("İptal",null).show();}
 private void newVirtualFile(){final EditText n=new EditText(this);n.setHint("dosya adı.txt");new AlertDialog.Builder(this).setTitle("Yeni dosya").setView(n).setPositiveButton("Oluştur",(d,w)->{String name=n.getText().toString().trim();if(name.isEmpty())return;try{new File(getWorkspace(),name).createNewFile();showWorkspace();}catch(Exception e){info.setText("Dosya oluşturma hatası: "+e.getMessage());}}).setNegativeButton("İptal",null).show();}
 private void newVirtualFolder(){final EditText n=new EditText(this);n.setHint("klasör adı");new AlertDialog.Builder(this).setTitle("Yeni klasör").setView(n).setPositiveButton("Oluştur",(d,w)->{String name=n.getText().toString().trim();if(name.isEmpty())return;try{new File(getWorkspace(),name).mkdirs();showWorkspace();}catch(Exception e){info.setText("Klasör hatası: "+e.getMessage());}}).setNegativeButton("İptal",null).show();}
 private File getWorkspace(){File d=new File(getFilesDir(),"editor_workspace/"+file.getName());d.mkdirs();return d;}
 private void showWorkspace(){list.removeAllViews();TextView back=t("‹ İçeriğe dön",16,Color.WHITE);back.setOnClickListener(v->load());list.addView(back);File[] fs=getWorkspace().listFiles();if(fs==null)fs=new File[0];Arrays.sort(fs,(a,b)->a.getName().compareToIgnoreCase(b.getName()));for(File f:fs){TextView r=t((f.isDirectory()?"▸ ":"  ")+f.getName(),16,Color.WHITE);r.setPadding(14,4,8,4);r.setOnClickListener(v->{if(f.isDirectory())showWorkspaceDir(f);else editWorkspace(f);});list.addView(r,new LinearLayout.LayoutParams(-1,58));}TextView note=t("Bu alan DEX/ARSC içine geçersiz sahte dosya enjekte etmez; yeni dosya/klasörleri düzenlemek için güvenli çalışma alanıdır.",12,Color.LTGRAY);note.setPadding(8,10,8,10);list.addView(note);}
 private void showWorkspaceDir(File dir){list.removeAllViews();TextView back=t("‹ Geri",16,Color.WHITE);back.setOnClickListener(v->showWorkspace());list.addView(back);File[] fs=dir.listFiles();if(fs!=null){Arrays.sort(fs,(a,b)->a.getName().compareToIgnoreCase(b.getName()));for(File f:fs){TextView r=t((f.isDirectory()?"▸ ":"  ")+f.getName(),16,Color.WHITE);r.setPadding(14,4,8,4);r.setOnClickListener(v->{if(f.isDirectory())showWorkspaceDir(f);else editWorkspace(f);});list.addView(r,new LinearLayout.LayoutParams(-1,58));}}}
 private void editWorkspace(File f){try{String s=new String(readAll(f),StandardCharsets.UTF_8);final EditText e=new EditText(this);e.setText(s);e.setTextColor(Color.WHITE);e.setGravity(Gravity.TOP);e.setSingleLine(false);new AlertDialog.Builder(this).setTitle(f.getName()).setView(e).setPositiveButton("Kaydet",(d,w)->{try(FileOutputStream o=new FileOutputStream(f)){o.write(e.getText().toString().getBytes(StandardCharsets.UTF_8));info.setText("Kaydedildi: "+f.getName());}catch(Exception x){info.setText("Kaydetme hatası: "+x.getMessage());}}).setNegativeButton("Çık",null).show();}catch(Exception e){info.setText("Açma hatası: "+e.getMessage());}}
 private byte[] readAll(File f)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();try(InputStream in=new FileInputStream(f)){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);}return o.toByteArray();}
 private void saveData(){if(pending==null){info.setText("Kaydedilecek değişiklik yok.");return;}try(FileOutputStream out=new FileOutputStream(file,false)){out.write(pending);pending=null;load();Toast.makeText(this,"Kaydedildi: "+file.getName(),Toast.LENGTH_SHORT).show();}catch(Exception e){info.setText("Kaydetme hatası: "+e.getMessage());}}
 private int indexOf(byte[] d,byte[] n,int from){outer:for(int i=Math.max(0,from);i<=d.length-n.length;i++){for(int j=0;j<n.length;j++)if(d[i+j]!=n[j])continue outer;return i;}return -1;}
}