package com.musab.dosyayoneticisi;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.Drawable;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;import androidx.core.content.FileProvider;import java.io.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity{
 LinearLayout root,list,actionBar; EditText pathEdit,searchEdit; File current,clipboard; boolean cutMode=false; float downX,downY; final File STORAGE=Environment.getExternalStorageDirectory(),MUSAB=new File(STORAGE,"MusabFolder"),APKS=new File(MUSAB,"apks"); int pad=18; boolean gridView=false,sortBySize=false; final int BG=Color.rgb(10,10,12),PANEL=Color.rgb(24,24,28),FG=Color.WHITE;
 public void onCreate(Bundle b){super.onCreate(b);ensureMusabFolders();current=STORAGE;build();requestStorageAccess();refresh();}
 void ensureMusabFolders(){MUSAB.mkdirs();APKS.mkdirs();}
 void requestStorageAccess(){if(Build.VERSION.SDK_INT>=30&&!Environment.isExternalStorageManager()){try{startActivity(new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,Uri.parse("package:"+getPackageName())));}catch(Exception ignored){}}else if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.WRITE_EXTERNAL_STORAGE")!=0)requestPermissions(new String[]{"android.permission.READ_EXTERNAL_STORAGE","android.permission.WRITE_EXTERNAL_STORAGE"},10);}
 TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(FG);t.setPadding(pad,pad,pad,pad);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL); root.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN){downX=e.getX();downY=e.getY();}else if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-downX,dy=e.getY()-downY;if(Math.abs(dx)>180&&Math.abs(dx)>Math.abs(dy)*1.3f&&dx>0){goParent();return true;}}return false;});root.setBackgroundColor(BG);root.addView(tv("MusabDosya Yöneticisi",25));
  LinearLayout nav=new LinearLayout(this);Button back=btn("Geri");back.setOnClickListener(v->goParent());pathEdit=new EditText(this);pathEdit.setSingleLine(true);pathEdit.setTextSize(17);pathEdit.setTextColor(FG);pathEdit.setHintTextColor(Color.GRAY);pathEdit.setImeOptions(5);pathEdit.setOnEditorActionListener((v,id,e)->{navigate(pathEdit.getText().toString());return true;});Button go=btn("Git");go.setOnClickListener(v->navigate(pathEdit.getText().toString()));nav.addView(back,new LinearLayout.LayoutParams(72,-2));nav.addView(pathEdit,new LinearLayout.LayoutParams(0,-2,1));nav.addView(go,new LinearLayout.LayoutParams(68,-2));root.addView(nav);
  LinearLayout searchRow=new LinearLayout(this);searchEdit=new EditText(this);searchEdit.setSingleLine(true);searchEdit.setHint("Ara...");searchEdit.setTextColor(FG);Button search=btn("Ara");search.setOnClickListener(v->refresh());searchRow.addView(searchEdit,new LinearLayout.LayoutParams(0,-2,1));searchRow.addView(search);root.addView(searchRow);
  actionBar=new LinearLayout(this);String[] actions={"Yeni","Yapıştır","Araçlar","Görünüm"};for(String s:actions){Button b=btn(s);if(s.equals("Yeni"))b.setOnClickListener(v->newDialog());if(s.equals("Yapıştır"))b.setOnClickListener(v->paste());if(s.equals("Araçlar"))b.setOnClickListener(v->toolsDialog());if(s.equals("Görünüm"))b.setOnClickListener(v->viewDialog());actionBar.addView(b,new LinearLayout.LayoutParams(0,-2,1));}root.addView(actionBar);
  ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void navigate(String p){if(p==null||p.trim().isEmpty())return;File f=new File(p.trim());if(!f.isAbsolute())f=new File(STORAGE,p.trim());try{if(f.isDirectory()){current=f.getCanonicalFile();refresh();}else toast("Dizin bulunamadı");}catch(Exception e){toast(e.getMessage());}}
 void goParent(){if(current!=null&&current.getParentFile()!=null){current=current.getParentFile();refresh();}}
 void refresh(){pathEdit.setText(current.getAbsolutePath());pathEdit.setSelection(pathEdit.length());list.removeAllViews();String q=searchEdit==null?"":searchEdit.getText().toString().trim().toLowerCase(Locale.ROOT);File[] fs=current.listFiles();if(fs==null){list.addView(tv("Erişim yok veya klasör boş.",16));return;}Arrays.sort(fs,(a,b)->{if(sortBySize&&!a.isDirectory()&&!b.isDirectory())return Long.compare(b.length(),a.length());if(a.isDirectory()!=b.isDirectory())return a.isDirectory()?-1:1;return a.getName().compareToIgnoreCase(b.getName());});int shown=0;for(File f:fs){if(!q.isEmpty()&&!f.getName().toLowerCase(Locale.ROOT).contains(q))continue;addItem(f);shown++;}if(shown==0)list.addView(tv("Sonuç yok.",16));}
 boolean specialName(File f){return f.getName().equals("Şirin")||f.getName().equals("Sirin");}
 int iconFor(File f){if(specialName(f))return com.musab.dosyayoneticisi.R.drawable.ic_cute;return f.isDirectory()?R.drawable.ic_folder:R.drawable.ic_file;}
 void addItem(File f){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(8,4,8,4);ImageView icon=new ImageView(this);icon.setImageResource(iconFor(f));TextView name=tv(f.getName(),18);row.addView(icon,new LinearLayout.LayoutParams(56,70));row.addView(name,new LinearLayout.LayoutParams(0,70,1));TextView size=tv(f.isDirectory()?"":human(f.length()),12);row.addView(size,new LinearLayout.LayoutParams(90,70));row.setBackgroundColor(PANEL);row.setPadding(4,2,4,2);row.setOnClickListener(v->{if(f.isDirectory()){current=f;refresh();}else openFile(f);});row.setOnLongClickListener(v->{fileMenu(f);return true;});list.addView(row,new LinearLayout.LayoutParams(-1,78));}
 String human(long n){if(n<1024)return n+" B";if(n<1024*1024)return String.format(Locale.US,"%.1f KB",n/1024d);if(n<1024L*1024*1024)return String.format(Locale.US,"%.1f MB",n/1024d/1024d);return String.format(Locale.US,"%.1f GB",n/1024d/1024d/1024d);}
 void openFile(File f){if(f.getName().equals("Salak.png")){makeSalakPng(f);return;}String x=f.getName().toLowerCase(Locale.ROOT);try{Intent i;if(isText(x))i=new Intent(this,MusabTextActivity.class);else if(isImage(x))i=new Intent(this,MusabImageViewerActivity.class);else if(isVideo(x))i=new Intent(this,MusabVideoViewerActivity.class);else if(isAudio(x))i=new Intent(this,MusabAudioPlayerActivity.class);else{i=new Intent(Intent.ACTION_VIEW);Uri u=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);i.setDataAndType(u,getMime(x));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);}if(isText(x)||isImage(x)||isVideo(x)||isAudio(x))i.putExtra("path",f.getAbsolutePath());startActivity(i);}catch(Exception e){toast("Dosya açılamadı: "+e.getMessage());}}
 boolean isText(String x){return x.endsWith(".txt")||x.endsWith(".xml")||x.endsWith(".json")||x.endsWith(".java")||x.endsWith(".kt")||x.endsWith(".gradle")||x.endsWith(".smali")||x.endsWith(".properties")||x.endsWith(".md")||x.endsWith(".js")||x.endsWith(".html")||x.endsWith(".css")||x.endsWith(".py")||x.endsWith(".yml")||x.endsWith(".yaml")||x.endsWith(".ini")||x.endsWith(".cfg")||x.endsWith(".sh")||x.endsWith(".c")||x.endsWith(".cpp")||x.endsWith(".h")||x.endsWith(".hpp");}
 boolean isImage(String x){return x.endsWith(".png")||x.endsWith(".jpg")||x.endsWith(".jpeg")||x.endsWith(".gif")||x.endsWith(".webp")||x.endsWith(".bmp")||x.endsWith(".heic");}
 boolean isVideo(String x){return x.endsWith(".mp4")||x.endsWith(".mkv")||x.endsWith(".webm")||x.endsWith(".3gp")||x.endsWith(".avi")||x.endsWith(".mov")||x.endsWith(".m4v");}
 boolean isAudio(String x){return x.endsWith(".mp3")||x.endsWith(".wav")||x.endsWith(".ogg")||x.endsWith(".m4a")||x.endsWith(".aac")||x.endsWith(".flac")||x.endsWith(".opus");}
 String getMime(String x){if(isImage(x))return "image/*";if(isVideo(x))return "video/*";if(isAudio(x))return "audio/*";if(x.endsWith(".apk"))return "application/vnd.android.package-archive";if(isText(x))return "text/plain";return "*/*";}
 void newDialog(){new AlertDialog.Builder(this).setTitle("Yeni").setItems(new String[]{"Klasör","Dosya"},(d,w)->{if(w==0)newFolder();else newFile();}).show();}
 void newFolder(){prompt("Yeni klasör adı","",s->{File f=new File(current,s);if(!f.mkdir())toast("Oluşturulamadı");refresh();});}
 void newFile(){prompt("Yeni dosya adı","",s->{try{new File(current,s).createNewFile();refresh();}catch(Exception e){toast(e.getMessage());}});}
 void prompt(String title,String value,Callback cb){EditText e=new EditText(this);e.setText(value);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Tamam",(d,w)->{String s=e.getText().toString().trim();if(!s.isEmpty())cb.run(s);}).setNegativeButton("İptal",null).show();}
 interface Callback{void run(String s);}
 void fileMenu(File f){String[] a={"Aç","Yeniden adlandır","Kopyala","Kes","Sil","Özellikler","Paylaş","ZIP oluştur"};new AlertDialog.Builder(this).setTitle(f.getName()).setItems(a,(d,w)->{switch(w){case 0:openFile(f);break;case 1:rename(f);break;case 2:clipboard=f;cutMode=false;toast("Kopyalandı");break;case 3:clipboard=f;cutMode=true;toast("Kesildi");break;case 4:confirmDelete(f);break;case 5:properties(f);break;case 6:share(f);break;case 7:zipSingle(f);break;}}).show();}
 void rename(File f){prompt("Yeniden adlandır",f.getName(),s->{if(!f.renameTo(new File(f.getParentFile(),s)))toast("Ad değiştirilemedi");refresh();});}
 void confirmDelete(File f){new AlertDialog.Builder(this).setTitle("Silinsin mi?").setMessage(f.getAbsolutePath()).setPositiveButton("Sil",(d,w)->{deleteRecursive(f);refresh();}).setNegativeButton("İptal",null).show();}
 void deleteRecursive(File f){if(f.isDirectory()){File[] c=f.listFiles();if(c!=null)for(File x:c)deleteRecursive(x);}f.delete();}
 void properties(File f){new AlertDialog.Builder(this).setTitle("Özellikler").setMessage("Yol: "+f.getAbsolutePath()+"\nBoyut: "+human(f.length())+"\nSon değişiklik: "+new Date(f.lastModified())).setPositiveButton("Tamam",null).show();}
 void share(File f){try{Uri u=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);Intent i=new Intent(Intent.ACTION_SEND);i.setType(getMime(f.getName().toLowerCase(Locale.ROOT)));i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Paylaş"));}catch(Exception e){toast(e.getMessage());}}
 void paste(){if(clipboard==null){toast("Panoda dosya yok");return;}File dst=new File(current,clipboard.getName());try{if(dst.exists())deleteRecursive(dst);copyRecursive(clipboard,dst);if(cutMode)deleteRecursive(clipboard);clipboard=null;refresh();}catch(Exception e){toast("Yapıştırma hatası: "+e.getMessage());}}
 void copyRecursive(File a,File b)throws Exception{if(a.isDirectory()){b.mkdirs();File[] c=a.listFiles();if(c!=null)for(File x:c)copyRecursive(x,new File(b,x.getName()));}else{InputStream in=new FileInputStream(a);OutputStream out=new FileOutputStream(b);byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();out.close();}}
 void zipSingle(File f){File out=new File(current,f.getName()+".zip");try{ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out));zipRec(f,z,f.getName());z.close();refresh();}catch(Exception e){toast("ZIP hatası: "+e.getMessage());}}
 void zipRec(File f,ZipOutputStream z,String path)throws Exception{if(f.isDirectory()){File[] c=f.listFiles();if(c==null||c.length==0){z.putNextEntry(new ZipEntry(path+"/"));z.closeEntry();}else for(File x:c)zipRec(x,z,path+"/"+x.getName());}else{z.putNextEntry(new ZipEntry(path));InputStream in=new FileInputStream(f);byte[] b=new byte[8192];int n;while((n=in.read(b))>0)z.write(b,0,n);in.close();z.closeEntry();}}
 void apps(){final PackageManager pm=getPackageManager();LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);TextView count=tv("Uygulamalar yükleniyor...",16);l.addView(count);ScrollView s=new ScrollView(this);s.addView(l);new AlertDialog.Builder(this).setTitle("APK Çıkar").setView(s).setPositiveButton("Kapat",null).show();new Thread(()->{List<ApplicationInfo> all=pm.getInstalledApplications(PackageManager.GET_META_DATA);all.sort((a,b)->String.valueOf(a.loadLabel(pm)).compareToIgnoreCase(String.valueOf(b.loadLabel(pm))));runOnUiThread(()->{l.removeAllViews();long uc=all.stream().filter(a->(a.flags&ApplicationInfo.FLAG_SYSTEM)==0).count(),sc=all.size()-uc;Button user=btn("Kullanıcı Uygulamaları ("+uc+")"),sys=btn("Sistem Uygulamaları ("+sc+")");l.addView(user);l.addView(sys);LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);l.addView(results);count.setText("Toplam görünür uygulama: "+all.size());user.setOnClickListener(v->showAppsList(results,all,false,pm));sys.setOnClickListener(v->showAppsList(results,all,true,pm));showAppsList(results,all,false,pm);});}).start();}
 void showAppsList(LinearLayout l,List<ApplicationInfo> all,boolean system,PackageManager pm){l.removeAllViews();l.addView(tv(system?"Tüm sistem uygulamaları":"Tüm kullanıcı uygulamaları",18));int shown=0;for(ApplicationInfo ai:all){boolean isSystem=(ai.flags&ApplicationInfo.FLAG_SYSTEM)!=0;if(isSystem!=system)continue;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);ImageView iv=new ImageView(this);Drawable d=ai.loadIcon(pm);iv.setImageDrawable(d);TextView t=tv(String.valueOf(ai.loadLabel(pm))+"\n"+ai.packageName,16);row.addView(iv,new LinearLayout.LayoutParams(58,64));row.addView(t,new LinearLayout.LayoutParams(0,64,1));row.setOnClickListener(v->appDetails(ai,pm));l.addView(row);shown++;}if(shown==0)l.addView(tv("Bu kategoride uygulama bulunamadı.",16));}
 void appDetails(ApplicationInfo ai,PackageManager pm){String label=String.valueOf(ai.loadLabel(pm));PackageInfo pi;try{pi=pm.getPackageInfo(ai.packageName,0);}catch(Exception e){toast("Uygulama bilgisi okunamadı");return;}long vc=Build.VERSION.SDK_INT>=28?pi.getLongVersionCode():pi.versionCode;File apk=new File(ai.sourceDir);String msg=label+"\n"+ai.packageName+"\nSürüm: "+pi.versionName+" ("+vc+")\nTemel APK: "+ai.sourceDir+"\nBoyut: "+human(apk.length())+"\nEk APK parçaları: "+(ai.splitSourceDirs==null?0:ai.splitSourceDirs.length);new AlertDialog.Builder(this).setTitle("Uygulama").setMessage(msg).setPositiveButton("APK Çıkar",(d,w)->extractApk(ai)).setNeutralButton("APK içeriği",(d,w)->apkContents(apk)).setNegativeButton("Kapat",null).show();}
 void extractApk(ApplicationInfo ai){ensureMusabFolders();String safe=ai.packageName.replaceAll("[^A-Za-z0-9._-]","_");File dir=new File(APKS,safe+"-"+System.currentTimeMillis());dir.mkdirs();try{copyRecursive(new File(ai.sourceDir),new File(dir,"base.apk"));if(ai.splitSourceDirs!=null)for(int n=0;n<ai.splitSourceDirs.length;n++)copyRecursive(new File(ai.splitSourceDirs[n]),new File(dir,"split-"+n+".apk"));toast("APK çıkarıldı: "+dir.getAbsolutePath());}catch(Exception e){toast("APK çıkarma hatası: "+e.getMessage());}}
 void toolsDialog(){ArrayList<String> a=new ArrayList<>();a.add("APK Çıkar / Uygulamalar");a.add("APK Arşiv İçeriği");a.add("Python editörü");a.add("IPython editörü");a.add("Pillow editörü");a.add("AndroidManifest / XML");a.add("MusabFolder'a git");new AlertDialog.Builder(this).setTitle("Musab Araçları").setItems(a.toArray(new String[0]),(d,w)->{if(w==0)apps();else if(w==1)apkContentsDialog();else if(w>=2&&w<=4)codeEditor(a.get(w));else if(w==5)terminal();else if(w==6)xmlEditor();else{current=MUSAB;refresh();}}).show();}
 void apkContentsDialog(){prompt("APK yolu","",p->{File f=new File(p);if(f.isFile())apkContents(f);else toast("APK bulunamadı");});}
 void codeEditor(String type){EditText e=new EditText(this);e.setGravity(Gravity.TOP);e.setMinLines(18);e.setTextSize(14);e.setHint(type+" kodu");new AlertDialog.Builder(this).setTitle(type+" editörü").setView(e).setPositiveButton("Dosyaya kaydet",(d,w)->prompt("Dosya adı",type.toLowerCase(Locale.ROOT)+".txt",n->{try{write(new File(current,n),e.getText().toString());refresh();}catch(Exception x){toast(x.getMessage());}})).setNegativeButton("Kapat",null).show();}
 void xmlEditor(){codeEditor("AndroidManifest / XML");}
 void terminal(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.BLACK);TextView h=tv("Musab Terminal",20);h.setTextColor(Color.WHITE);r.addView(h);TextView p=tv(current.getAbsolutePath(),13);p.setTextColor(Color.LTGRAY);r.addView(p);ScrollView sv=new ScrollView(this);TextView out=tv("Musab Terminal\\n$ ",14);out.setTextColor(Color.WHITE);sv.addView(out);r.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout line=new LinearLayout(this);EditText in=new EditText(this);in.setSingleLine(true);in.setTextColor(Color.WHITE);in.setHintTextColor(Color.GRAY);in.setHint("komut");Button run=btn("Çalıştır");line.addView(in,new LinearLayout.LayoutParams(0,-2,1));line.addView(run);r.addView(line);Button back=btn("Dosya Yöneticisine Dön");back.setOnClickListener(v->setContentView(root));r.addView(back);setContentView(r);run.setOnClickListener(v->{String cmd=in.getText().toString().trim();if(cmd.isEmpty())return;out.append(cmd+"\\n"+localCommand(cmd)+"\\n$ ");in.setText("");sv.post(()->sv.fullScroll(View.FOCUS_DOWN));});}
String localCommand(String cmd){try{if(cmd.equals("pwd"))return current.getAbsolutePath();if(cmd.equals("ls")){File[] fs=current.listFiles();if(fs==null)return "Erişim yok";StringBuilder s=new StringBuilder();for(File f:fs)s.append(f.isDirectory()?"[D] ":"[F] ").append(f.getName()).append("\\n");return s.toString();}if(cmd.startsWith("cd ")){File f=new File(current,cmd.substring(3).trim());if(f.isDirectory()){current=f.getCanonicalFile();return "Dizin değişti: "+current;}return "Dizin bulunamadı";}if(cmd.equals("clear"))return "";if(cmd.equals("help"))return "pwd, ls, cd <klasör>, clear, help";return "Komut desteklenmiyor";}catch(Exception e){return "Hata: "+e.getMessage();}}
void viewDialog(){new AlertDialog.Builder(this).setTitle("Görünüm").setItems(new String[]{"Liste","Büyük simgeler","Sırala: ad","Sırala: boyut","Yenile"},(d,w)->{if(w==0){gridView=false;refresh();}else if(w==1){gridView=true;refresh();}else if(w==2){sortBySize=false;refresh();}else if(w==3){sortBySize=true;refresh();}else refresh();}).show();}
 void makeSalakPng(File f){try{Bitmap b=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Random r=new Random();for(int y=0;y<512;y++)for(int x=0;x<512;x++)b.setPixel(x,y,Color.rgb(r.nextInt(256),r.nextInt(256),r.nextInt(256)));FileOutputStream o=new FileOutputStream(f);b.compress(Bitmap.CompressFormat.PNG,100,o);o.close();openFile(f);}catch(Exception e){toast("PNG oluşturulamadı: "+e.getMessage());}}
 void write(File f,String s)throws Exception{FileOutputStream o=new FileOutputStream(f,false);o.write(s.getBytes("UTF-8"));o.close();}
 void apkContents(File f){try{ZipFile z=new ZipFile(f);StringBuilder s=new StringBuilder();Enumeration<? extends ZipEntry> en=z.entries();while(en.hasMoreElements())s.append(en.nextElement().getName()).append('\n');z.close();new AlertDialog.Builder(this).setTitle("APK içeriği").setMessage(s.toString()).setPositiveButton("Kapat",null).show();}catch(Exception e){toast("APK okunamadı: "+e.getMessage());}}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}